
import time

def titleArt():
    print("  __  __     ______     ______     __  __     ______     ______    ")
    print(" /\ \_\ \   /\  __ \   /\  ___\   /\ \/ /    /\  ___\   /\  == \   ")
    print(" \ \  __ \  \ \  __ \  \ \ \____  \ \  _'-.  \ \  __\   \ \  __<   ")
    print("  \ \_\ \_\  \ \_\ \_\  \ \_____\  \ \_\ \_\  \ \_____\  \ \_\ \_\ ")
    print("   \/_/\/_/   \/_/\/_/   \/_____/   \/_/\/_/   \/_____/   \/_/ /_/ ")

def skullArt():
    print("                        uuuuuuu ")
    print("                    uu$$$$$$$$$$$uu")
    print("                   uu$$$$$$$$$$$$$$$$$uu")
    print("                 u$$$$$$$$$$$$$$$$$$$$$u")
    print("                u$$$$$$$$$$$$$$$$$$$$$$$u")
    print("              u$$$$$$$$$$$$$$$$$$$$$$$$$u")
    print("              u$$$$$$$$$$$$$$$$$$$$$$$$$u")
    print("              u$$$$$$"   "$$$"   "$$$$$$u")
    print("              '$$$$'      u$u       $$$$" )
    print("               $$$u       u$u       u$$$")
    print("               $$$u      u$$$u      u$$$")
    print("                '$$$$uu$$$   $$$uu$$$$'")
    print("                 '$$$$$$$"   "$$$$$$$'")
    print("                   u$$$$$$$u$$$$$$$u")
    print("                    u$'$'$'$'$'$'$u")
    print("         uuu        $$u$ $ $ $ $u$$       uuu")
    print("        u$$$$        $$$$$u$u$u$$$       u$$$$")
    print("         $$$$$uu      '$$$$$$$$$'     uu$$$$$$")
    print("       u$$$$$$$$$$$uu    '''''    uuuu$$$$$$$$$$")
    print("       $$$$'''$$$$$$$$$$uuu   uu$$$$$$$$$'''$$$'")
    print("        '''      ''$$$$$$$$$$$uu ''$'''")
    print("                  uuuu ""$$$$$$$$$$uuu")
    print("         u$$$uuu$$$$$$$$$uu ""$$$$$$$$$$$uuu$$$")
    print("         $$$$$$$$$$''''           ''$$$$$$$$$$$'")
    print("          '$$$$$'                      ""$$$$""")
    print("            $$$'                         $$$$'")
    print(" _______  _______  _______  _______  _______  _______ ")
    print("|   _   ||       ||       ||       ||       ||       |")
    print("|  |_|  ||       ||       ||    ___||  _____||  _____|")
    print("|       ||       ||       ||   |___ | |_____ | |_____ ")
    print("|       ||      _||      _||    ___||_____  ||_____  |")
    print("|   _   ||     |_ |     |_ |   |___  _____| | _____| |")
    print("|__| |__||_______||_______||_______||_______||_______|")
    print("   ______   _______  __    _  ___   _______  ______     ")
    print("  |      | |       ||  |  | ||   | |       ||      |    ")
    print("  |  _    ||    ___||   |_| ||   | |    ___||  _    |   ")
    print("  | | |   ||   |___ |       ||   | |   |___ | | |   |   ")
    print("  | |_|   ||    ___||  _    ||   | |    ___|| |_|   |   ")
    print("  |       ||   |___ | | |   ||   | |   |___ |       |   ")
    print("  |______| |_______||_|  |__||___| |_______||______|   ")

def sadArt():
    print("     .-''''''-.")
    print("   .'          '.")
    print("  /   O      O   | ")
    print(" :           `    :")
    print(" |                |  ") 
    print(" :    .------.    :")
    print("  \  '        '  /")
    print("   '.          .'")
    print("     '-......-'")

def compArt():
    print("  ___________")
    print(" |.---------.|")
    print(" ||         ||")
    print(" ||         ||")
    print(" ||         ||")
    print(" |'---------'|")
    print("  `)__ ____(' ")
    print("  [=== -- o ]--.")
    print("__'---------'__ ")
    print("[::::::::::: :::] ")
    print("`""'"""""'""""`")
def nameArt2():
    print(" _  __    _ _          _____          ___ ___  _     ")
    print("| |/ /   | | |        / ____|        |__ \__ \| |    ")
    print("| ' / ___| | |_   _  | (___  _ __ ___   ) | ) | |__  ")
    print("|  < / _ \ | | | | |  \___ \| '_ ` _ \ / / / /| '_ \ ")
    print("| . \  __/ | | |_| |  ____) | | | | | |_| |_| | | | |")
    print("|_|\_\___|_|_|\__, | |_____/|_| |_| |_(_) (_) |_| |_|")
    print("               __/ |                                 ")
    print("              |___/                                  ")


def photoArt():
    print("       _       _       _       _       _       _       _       _")
    print("  .-'-._,-'_`-._,-'_`-._,-'_`-._,-'_`-,_,-'_`-,_,-'_`-,_,-'_`-,_,-'_`-,")
    print(" (  ,-'_,-'.>-'_,-   '_,- .>-'    .>-'_,-~.=-'_,-~.=-'_,-~.=-'_,-~-} ;")
    print("  \ \.'_>-._`-<_>-._`-<_>-._`-<_>-._`-._=-._`-._=-._'-._=-._`-._~--.  ")
    print("  /\ \/ ,-' `-._,-' `-._,-' `-._,-' `-._,-' `-._,-' `-._,-' `-._`./ \\")
    print(" ( (`/ /                                                        `/ /.) )")
    print("  \ \ / \                                                       / / \ /")
    print("   \ ') )                                                       ( (,\ ")
    print("  / \ / /                                                       \ / \ ")
    print(" ( (`/ /                                                        / /.) )")
    print("  \ \ / \                    ,=""=,                             / / \ /")
    print("   \ ') )                   c , _,{                            ( (,\ ")
    print("  / \ / /                   /\  @ )                 __          \ / \ ")
    print(" ( (`/ /                   /  ^~~^\          <=.,__/ '}=         / /.) )")
    print("  \ \ / \                 (_/ ,, ,,)          \_ _>_/~          / / \ /")
    print("   \ ') )                  ~\_(/-\)'-,_,_,_,-'(_)-(_)          ( (,\  ")
    print("  / \ y /                                                       \ y \  ")
    print(" ( ( y /                                                         y /.) )")
    print("  \ \ / \                                                       / / \ /")
    print("   \ ') )                                                      ( (,\  ")
    print("  / \ / /                                                       \ / \  ")
    print(" ( (`/ /                                                         / /.) )")
    print("  \ \ / \                                                       / / \ /")
    print("   \ `.\ `-   ________  ______   ______   _____  ________")
    print("             |_   __  ||_   _ `.|_   _ `.|_   _||_   __  | ")
    print("               | |_ \_|  | | `. \ | | `. \ | |    | |_ \_| ")
    print("               |  _| _   | |  | | | |  | | | |    |  _| _  ")
    print("              _| |__/ | _| |_.' /_| |_.' /_| |_  _| |__/ | ")
    print("             |________||______.'|______.'|_____||________|")

def kesArt():
    print("  ___   _  _______  _______ ")
    print(" |   | | ||       ||       |")
    print(" |   |_| ||    ___||  _____|")
    print(" |      _||   |___ | |_____ ")
    print(" |     |_ |    ___||_____  |")
    print(" |    _  ||   |___  _____| |")
    print(" |___| |_||_______||_______|")

def kesArt2():
    print("@ ___   _  _______  _______ ")
    print(" |   | | ||       ||       |")
    print(" |   |_| ||    ___||  _____|")
    print(" |      _||   |___ | |_____ ")
    print(" |     |_ |    ___||_____  |")
    print(" |    _  ||   |___  _____| |")
    print(" |___| |_||_______||_______|.com")

def eyeArt():
    print("                        __..--.._")
    print("  .....              .--~  .....  `.")
    print(".':    '`-..  .    .' ..-''    :'. `")
    print("` `._ ` _.'`'(     `-''`._ ' _.' '")
    print("     ~~~      `.          ~~~")
    print("              .'")
    print("             /")
    print("            (")
    print("             ^---'")

def noteArt():
    print(" _______  _     _  _______  ______    ______     ____  ")                                
    print("|       || | _ | ||       ||    _ |  |      |   |____| ")                                
    print("|    _  || || || ||   _   ||   | ||  |  _    |   ____   ")                               
    print("|   |_| ||       ||  | |  ||   |_||_ | | |   |  |____|  ")                               
    print("|    ___||       ||  |_|  ||    __  || |_|   |           ")                              
    print("|   |    |   _   ||       ||   |  | ||       |           ")                              
    print("|___|    |__| |__||_______||___|  |_||______|             ")                             
    print(" _______  _______  _______  __   __      _       ______         _______        _______ ")
    print("|  _    ||   _   ||  _    ||  | |  |   _| |_    |      |       |       |      |  _    |")
    print("| |_|   ||  |_|  || |_|   ||  |_|  |  |_   _|   |  _    |      |   _   |      | |_|   |")
    print("|       ||       ||       ||       |    |_|     | | |   |      |  | |  |      |       |")
    print("|  _   | |       ||  _   | |_     _|            | |_|   | ___  |  |_|  | ___  |  _   | ")
    print("| |_|   ||   _   || |_|   |  |   |              |       ||   | |       ||   | | |_|   |")
    print("|_______||__| |__||_______|  |___|              |______| |___| |_______||___| |_______|")


def nameArt():
    print(" ___   _  _______  ___      ___      __   __ ")
    print("|   | | ||       ||   |    |   |    |  | |  |")
    print("|   |_| ||    ___||   |    |   |    |  |_|  |")
    print("|      _||   |___ |   |    |   |    |       |")
    print("|     |_ |    ___||   |___ |   |___ |_     _|")
    print("|    _  ||   |___ |       ||       |  |   |  ")
    print("|___| |_||_______||_______||_______|  |___|  ")
    print(" _______  __   __  ___   _______  __   __    ")
    print("|       ||  |_|  ||   | |       ||  | |  |   ")
    print("|  _____||       ||   | |_     _||  |_|  |   ")
    print("| |_____ |       ||   |   |   |  |       |   ")
    print("|_____  ||       ||   |   |   |  |       |   ")
    print(" _____| || ||_|| ||   |   |   |  |   _   |   ")
    print("|_______||_|   |_||___|   |___|  |__| |__|    ")

def googleArt():
    print(" _______  ______   ______   ___   _______   ")                  
    print("|       ||      | |      | |   | |       |   ")                 
    print("|    ___||  _    ||  _    ||   | |    ___|   ")                 
    print("|   |___ | | |   || | |   ||   | |   |___     ")                
    print("|    ___|| |_|   || |_|   ||   | |    ___|    ")                
    print("|   |___ |       ||       ||   | |   |___     ")                
    print("|_______||______| |______| |___| |_______|     ")               
    print(" _______  _______        ____   ____         _______  _______ ")
    print("|  _    ||       |      |    | |    |       |       ||  _    |")
    print("| | |   ||___    |       |   |  |   |       |____   || | |   |")
    print("| | |   |    |   |       |   |  |   |        ____|  || | |   |")
    print("| |_|   |    |   | ___   |   |  |   |  ___  | ______|| |_|   |")
    print("|       |    |   ||   |  |   |  |   | |   | | |_____ |       |")
    print("|_______|    |___||___|  |___|  |___| |___| |_______||_______|")

def phishingArt():
    print(" ___   _  _______  ___      ___      __   __  ")                            
    print("|   | | ||       ||   |    |   |    |  | |  |  ")                           
    print("|   |_| ||    ___||   |    |   |    |  |_|  |  ")                           
    print("|      _||   |___ |   |    |   |    |       |  ")                           
    print("|     |_ |    ___||   |___ |   |___ |_     _|  ")                           
    print("|    _  ||   |___ |       ||       |  |   |    ")                           
    print("|___| |_||_______||_______||_______|  |___|    ")                           
    print(" _______  __   __  ___   _______  __   __      ")                           
    print("|       ||  |_|  ||   | |       ||  | |  |     ")                           
    print("|  _____||       ||   | |_     _||  |_|  |     ")                           
    print("| |_____ |       ||   |   |   |  |       |      ")                          
    print("|_____  ||       ||   |   |   |  |       |      ")                          
    print(" _____| || ||_|| ||   |   |   |  |   _   |      ")                          
    print("|_______||_|   |_||___|   |___|  |__| |__|       ")                         
    print(" _______  _______  _______  _______  __   __    ")                          
    print("|       ||       ||       ||       ||  |_|  |    ")                         
    print("|    ___||  _____||  _____||    ___||       |    ")                         
    print("|   |___ | |_____ | |_____ |   |___ |       |    ")                         
    print("|    ___||_____  ||_____  ||    ___| |     |     ")                         
    print("|   |___  _____| | _____| ||   |___ |   _   |    ")                         
    print("|_______||_______||_______||_______||__| |__|     ")                        
    print(" _______  _______  _______    ____     ___      __   __  __    _  _______ ")
    print("|       ||       ||       |  |____|   |   |    |  | |  ||  |  | ||   _   |")
    print("|    _  ||    ___||_     _|   ____    |   |    |  | |  ||   |_| ||  |_|  |")
    print("|   |_| ||   |___   |   |    |____|   |   |    |  |_|  ||       ||       |")
    print("|    ___||    ___|  |   |             |   |___ |       ||  _    ||       |")
    print("|   |    |   |___   |   |             |       ||       || | |   ||   _   |")
    print("|___|    |_______|  |___|             |_______||_______||_|  |__||__| |__|")

def loginArt():
    print(" _______  __    _  _______  _______  ______   ")
    print("|       ||  |  | ||       ||       ||    _ |   ")
    print("|    ___||   |_| ||_     _||    ___||   | ||   ")
    print("|   |___ |       |  |   |  |   |___ |   |_||_  ")
    print("|    ___||  _    |  |   |  |    ___||    __  | ")
    print("|   |___ | | |   |  |   |  |   |___ |   |  | |  ")
    print("|_______||_|  |__|  |___|  |_______||___|  |_|  ")
    print(" _______  __   __  _______  ___   ___      ___  ")
    print("|       ||  |_|  ||   _   ||   | |   |    |   | ")
    print("|    ___||       ||  |_|  ||   | |   |    |___| ")
    print("|   |___ |       ||       ||   | |   |     ___  ")
    print("|    ___||       ||       ||   | |   |___ |   | ")
    print("|   |___ | ||_|| ||   _   ||   | |       ||___| ")
    print("|_______||_|   |_||__| |__||___| |_______|      ")


def passwordArt():
    print(" _______  __    _  _______  _______  ______      ")
    print("|       ||  |  | ||       ||       ||    _ |     ")
    print("|    ___||   |_| ||_     _||    ___||   | ||     ")
    print("|   |___ |       |  |   |  |   |___ |   |_||_    ")
    print("|    ___||  _    |  |   |  |    ___||    __  |  ")
    print("|   |___ | | |   |  |   |  |   |___ |   |  | | ")
    print("|_______||_|  |__|  |___|  |_______||___|  |_| ")
    print(" _______  _______  _______  _______  _     _  _______  ______    ______   ___  ")
    print("|       ||   _   ||       ||       || | _ | ||       ||    _ |  |      | |   | ")
    print("|    _  ||  |_|  ||  _____||  _____|| || || ||   _   ||   | ||  |  _    ||___| ")
    print("|   |_| ||       || |_____ | |_____ |       ||  | |  ||   |_||_ | | |   | ___  ")
    print("|    ___||       ||_____  ||_____  ||       ||  |_|  ||    __  || |_|   ||   | ")
    print("|   |    |   _   | _____| | _____| ||   _   ||       ||   |  | ||       ||___| ")
    print("|___|    |__| |__||_______||_______||__| |__||_______||___|  |_||______|       ")

def questionArt():
    print(" _     _  __   __  _______  _______    ___   _______    __   __  __   __   ")        
    print("| | _ | ||  | |  ||   _   ||       |  |   | |       |  |  |_|  ||  | |  |  ")        
    print("| || || ||  |_|  ||  |_|  ||_     _|  |   | |  _____|  |       ||  |_|  |  ")        
    print("|       ||       ||       |  |   |    |   | | |_____   |       ||       |  ")        
    print("|       ||       ||       |  |   |    |   | |_____  |  |       ||_     _|  ")        
    print("|   _   ||   _   ||   _   |  |   |    |   |  _____| |  | ||_|| |  |   |    ")        
    print("|__| |__||__| |__||__| |__|  |___|    |___| |_______|  |_|   |_|  |___|    ")        
    print(" _______  _______  _______  _______    __    _  _______  __   __  _______  ______ ") 
    print("|       ||   _   ||       ||       |  |  |  | ||   _   ||  |_|  ||       ||      |") 
    print("|       ||  |_|  ||_     _||  _____|  |   |_| ||  |_|  ||       ||    ___||___   |") 
    print("|       ||       |  |   |  | |_____   |       ||       ||       ||   |___   __|  | ")
    print("|      _||       |  |   |  |_____  |  |  _    ||       ||       ||    ___| |_____| ")
    print("|     |_ |   _   |  |   |   _____| |  | | |   ||   _   || ||_|| ||   |___    __    ")
    print("|_______||__| |__|  |___|  |_______|  |_|  |__||__| |__||_|   |_||_______|  |__|   ")

def entryArt():
    print(" _______  __    _  _______  ______    __   __   ")                     
    print("|       ||  |  | ||       ||    _ |  |  | |  |  ")                     
    print("|    ___||   |_| ||_     _||   | ||  |  |_|  |  ")                     
    print("|   |___ |       |  |   |  |   |_||_ |       |  ")                     
    print("|    ___||  _    |  |   |  |    __  ||_     _|  ")                     
    print("|   |___ | | |   |  |   |  |   |  | |  |   |    ")                     
    print("|_______||_|  |__|  |___|  |___|  |_|  |___|    ")                     
    print(" _______  ______    _______  __    _  _______  _______  ______   __  ")
    print("|       ||    _ |  |   _   ||  |  | ||       ||       ||      | |  | ")
    print("|    ___||   | ||  |  |_|  ||   |_| ||_     _||    ___||  _    ||  | ")
    print("|   | __ |   |_||_ |       ||       |  |   |  |   |___ | | |   ||  | ")
    print("|   ||  ||    __  ||       ||  _    |  |   |  |    ___|| |_|   ||__| ")
    print("|   |_| ||   |  | ||   _   || | |   |  |   |  |   |___ |       | __  ")
    print("|_______||___|  |_||__| |__||_|  |__|  |___|  |_______||______| |__| ")

def catArt():
    print("                                                                             .--.")
    print("                                                                            J    L")
    print("                                                                            |    |")
    print("                                                                            F    F")
    print("                                                                           J    J")
    print("                                                                          /    /")
    print("                                                                         /    /")
    print("                                                                       .'    /")
    print("                                               .--""--._              /     /")
    print("                                           _.-'         `-.          /     /")
    print("                                __       .'                `.       /     /")
    print("                             _-'-.'`-.  J                    \     /     /")
    print("                        .---(  `, _   `'|                     `.  J     /")
    print("                          `. )                                  ""     /")
    print("                           F                                          J")
    print("                           L                  |                      J")
    print("                           ` (/     /         |                      F")
    print("                            |    ._'          |                      |")
    print("                           /'`--'`.           |                      J")
    print("                           '||\   |-._        `.  ___.               |")
    print("                             `     \  `.        |/    `-            J")
    print("                                    F   L       /       J           /")
    print("                                    |   J      J         F         J")
    print("                                    |    \     J         |        J")
    print("                                    |    |L    J         J        J")
    print("                                    |    FJ    |          L       |")
    print("                                    |   J  L   |          L\      F")
    print("                                    |   F  |   |           L\    J")
    print("                                    F  F   |   |           | L   |")
    print("                                   J  J    |   |           | |   F")
    print("                                   /  )    F  J            F F  J")
    print("                                  ( .'    )   F           J J  F")
    print("                                  `'     (   J           /.'  J")
    print("                                          `-'           ||-' |)")
    print("                                                          '-'")

def hackArt():
    print(" __   __  _______  _______  ___   _  ")                                          
    print("|  | |  ||   _   ||       ||   | | |  ")                                         
    print("|  |_|  ||  |_|  ||       ||   |_| |   ")                                        
    print("|       ||       ||       ||      _|   ")                                        
    print("|       ||       ||      _||     |_     ")                                       
    print("|   _   ||   _   ||     |_ |    _  |    ")                                       
    print("|__| |__||__| |__||_______||___| |_|    ")                                       
    print(" _______  _______  __   __  _______  ___      _______  _______  _______ ")       
    print("|       ||       ||  |_|  ||       ||   |    |       ||       ||       | ")      
    print("|       ||   _   ||       ||    _  ||   |    |    ___||_     _||    ___|  ")     
    print("|       ||  | |  ||       ||   |_| ||   |    |   |___   |   |  |   |___    ")    
    print("|      _||  |_|  ||       ||    ___||   |___ |    ___|  |   |  |    ___|   ")    
    print("|     |_ |       || ||_|| ||   |    |       ||   |___   |   |  |   |___    ")    
    print("|_______||_______||_|   |_||___|    |_______||_______|  |___|  |_______|   ")    
    print(" _     _  _______  ___      ___        ______   _______  __    _  _______  __ ") 
    print("| | _ | ||       ||   |    |   |      |      | |       ||  |  | ||       ||  | ")
    print("| || || ||    ___||   |    |   |      |  _    ||   _   ||   |_| ||    ___||  | ")
    print("|       ||   |___ |   |    |   |      | | |   ||  | |  ||       ||   |___ |  | ")
    print("|       ||    ___||   |___ |   |___   | |_|   ||  |_|  ||  _    ||    ___||__| ")
    print("|   _   ||   |___ |       ||       |  |       ||       || | |   ||   |___  __  ")
    print("|__| |__||_______||_______||_______|  |______| |_______||_|  |__||_______||__| ")

def main():
    currentScore = 3
    titleArt()
    print("This game is designed to show you how you can socially engineer someone")
    print("Read the information about the person and gather information")
    print("When you think you have enough information, try to hack into their account")
    print("Be careful! You only get 3 chances!!...")
    x = input("Press any key to continue...\n")
    compArt()
    print("Here is the computer you are trying to hack...")
    print("You need a username and password...")
    userChoice = menu(currentScore)
    

def menu(currentScore):
    print("You have", currentScore, "attempts remaining...")
    print("What do you want to do?")
    print("1. Run a Brute Force Attack")
    print("2. Look around the desk")
    print("3. Look in the bin")
    print("4. Try googling")
    print("5. Look around the office")
    print("6. Look at the coffee cup")
    print("7. Look in the desk")
    print("8. Install a packet sniffer")
    print("9. Try a phishing attack")
    print("10. HACK INTO COMPUTER (Do this if you are sure you have the info needed) ")
    choice = input()
    actions(choice, currentScore)

def actions(userChoice, currentScore):
    if userChoice == "1":
        action1(currentScore)

    elif userChoice == "2":
        action2(currentScore)

    elif userChoice == "3":
        action3(currentScore)

    elif userChoice == "4":
        action4(currentScore)

    elif userChoice == "5":
        action5(currentScore)

    elif userChoice == "6":
        action6(currentScore)

    elif userChoice == "7":
        action7(currentScore)

    elif userChoice == "8":
        action8(currentScore)

    elif userChoice == "9":
        action9(currentScore)

    elif userChoice == "10":
        action10(currentScore)

    else:
        print("Just type between 1 and 10")
        userChoice = menu(currentScore)
        actions(userChoice)

def scoreUpdater(currentScore):
    currentScore = currentScore - 1
    if currentScore == 0:
        print("You FAILED Your mission!")
        sadArt()
        print("You have been arrested for breaking the computer misuse act!")
        print("GAME OVER!!!")
        x = input("Press Any Key you Criminal!")
        exit()
    else:
        print("You lost a chance!!")
        return currentScore
        
        
def action1(currentScore):
    print("You try and brute force it...")
    message = "ACCESS DENIED"
    messageList = []
    for x in range(0,len(message)):
        messageList.append(message[x])
        print(messageList)
    skullArt()
    print("Looks like that didnt work!")
    print("You'll have to social engineer this Hack!")
    print("Press Any Key to continue")
    x = input()
    currentScore = scoreUpdater(currentScore)
    menu(currentScore)
    

def action2(currentScore):
    print("You look around the desk...")
    print("There are a number of items scattered over the desk")
    print("There is a photo of a baby on the desk")
    print("The frame he is in has the word 'EDDIE' written on it...")
    print("Press Any Key to continue")
    x = input()
    photoArt()
    print("Press Any Key to continue")
    x = input()
    print("You notice the log on screen on the computer. It reads @KES.com")
    print("Press Any Key to continue")
    x = input()
    kesArt2()
    print("Press Any Key to continue")
    x = input()
    print("Thats good Info!")
    print("Make a note of it...")
    print("")
    menu(currentScore)

def action3(currentScore):
    print("You pick up the bin an have a rummage...")
    print("Maybe you should have waited to try this hack when the office was empty!")
    print("Other employees are eyeing you suspiciously...")
    eyeArt()
    print("Press Any Key to continue")
    x = input()
    print("Lets hope it was worth it!")
    print("You find a screwed up old note...")
    print("Press Any Key to continue")
    x = input()
    print("It reads:")
    noteArt()
    print("Press Any Key to continue")
    x = input()
    print("Whoa, who would leave valuable info like this lying around??")
    print("Make a note of this new info")
    print("Uh oh, all your bin diving has attracted some attention...")
    eyeArt()
    print("An angry looking security guard has appeared. They ask what you are doing...")
    print("How do you respond?")
    print("1. Say you work here, and this is your desk!")
    print("2. Say you are just here to empty the bins")
    print("3. Say you dropped a sandwich in the bin and are just fishing it out to finish it")
    
    choice = input()
    while choice != "1" and choice != "2" and choice !="3":
        print("You can only choose 1, 2 or 3...")
        print("1. Say you work here, and this is your desk!")
        print("2. Say you are just here to empty the bins")
        print("3. Say you dropped a sandwich in the bin and are just fishing it out to finish it")
        choice = input()

    if choice == "1":
        eyeArt()
        print("The guard eyes you suspiciously")
        print("He says:")
        print("I thought this was desk belonged to:")
        nameArt()
        print("Press Any Key to continue")
        x = input()
        print("He Continues...")
        print("I must be mistaken, carry on...")
        print("Press Any Key to continue")
        x = input()
        print("You got a name!")
        print("The weakest link in any network, are the humans!")
        print("Make a note of this new info!")
        print("")
        menu(currentScore)

    elif choice == "2":
        eyeArt()
        print("The guard eyes you suspiciously")
        print("He says:")
        print("Thats not right, your not dressed as a cleaner!")
        print("youve been rumbled!")
        print("You lose an attempt!")
        currentScore = scoreUpdater(currentScore)
        menu(currentScore)

    elif choice == "3":
        eyeArt()
        print("The guard eyes you suspiciously")
        print("He says:")
        print("You really shouldnt eat out of bins...thats just wrong...")
        print("He walks off leaving you to it")
        print("PHEW That was close!")
        print("")
        menu(currentScore)
    
def action4(currentScore):
    print("You try Googling for information...")
    print("You take out your smartphone and connect to the internet, thank goodness for 4G!")
    print("Whats can you google?")
    print("Do you know their name?")
    name = input("Type their name if you know it...if not, just hit ENTER\n")
    if name.upper() == "KELLY SMITH":
        print("Thats right, her name is Kelly Smith!")
        print("Now...what other information can we use...")
        print("Do we know where they work?")
        work = input("Type their work if you know it...if not, just hit ENTER\n")
        if work.upper() == "KES":
            print("Thats right, they work at KES!...")
            print("Okay, lets check facebook!")
            print("Well look at that, its a picture of Kelly Smith, with a baby")
            print("The caption reads:")
            googleArt()
            print("Press Any Key to continue")
            x = input()
            print("Whoa, thats good info!")
            print("Make a note of it!")
            print("")
            menu(currentScore)

        else:
            print("Hmmm maybe you need to do a bit more investigating...")
            print("")
            menu(currentScore)
        

    else:
        print("Hmmm what about where they work?...")
        work = input("Type their work if you know it...if not, just hit ENTER\n")
        if work.upper() == "KES":
            print("Thats right, they work at KES!")
            print("Ok, lets look at the staff list...")
            print("Press Any Key to continue")
            x = input()
            print("Jake Blagg - English Dept")
            print("Kelly Smith - Art Dept")
            print("Clare Jenkins - Maths Dept")
            print("Harry Sims - Deputy Head")
            print("Press Any Key to continue")
            x = input()
            print("Hmmmm, could one of these be our target?")
            print("Press Any Key to continue")
            x = input()
            menu(currentScore)


        else:
            print("Hmmm maybe you need to do a bit more investigating...")
            print("")
            menu(currentScore)

            
def action5(currentScore):
    print("You glance around the office...")
    print("Under closer inspection, you realise you are at KES!")
    kesArt()
    print("Press Any Key to continue")
    x = input()
    print("Good info, make a note of it!")
    print("Better not wander around, that security guard might get suspicious...")
    print("")
    menu(currentScore)
    

def action6(currentScore):
    print("Its a throw away coffee cup from starbucks")
    print("...I wonder if they wrote her name on it...")
    print("Press Any Key to continue")
    x = input()
    print("Turning the coffee cup over in your hands you can see a name...")
    print("Unfortunately, part of it is smudged, but you can make the following:")
    print("Press Any Key to continue")
    x = input()
    nameArt2()
    print("Press Any Key to continue")
    x = input()
    print("You can make out the following: kelly sm??h")
    print("Hmmm...the smudge means you can quiote make out the last name")
    print("Its probably a common last name, I wonder what it could be...")
    print("Press Any Key to continue")
    x = input()
    menu(currentScore)

def action7(currentScore):
    print("You try to open the desk drawers, but its locked...")
    print("Unfortunately, you messing with the desk has attracted the security guards attention!")
    eyeArt()
    print("Press Any Key to continue")
    x = input()
    print("The security guard is suspicious of you, play it cool!")
    print("He says:")
    print("Why are you messing with that desk?")
    print("You seem a bit...out of place...")
    print("Do you even work here?")
    print("You have 3 choice: 1, 2 or 3...")
    print("1. Of course I work here...at the NHS...")
    print("2. Of course I work here...at KES...")
    print("3. Of course I work here...at NASA...")
    job = input()
    while job != "1" and job != "2" and job !="3":
        print("You can only choose 1, 2 or 3...")
        print("1. Of course I work here...at the NHS...")
        print("2. Of course I work here...at KES...")
        print("3. Of course I work here...at NASA...")
        job = input()
        
    if job == "1":
        eyeArt()
        print("The security guard is not impressed")
        print("Press Any Key to continue")
        x = input()
        print("He says:")
        print("You dont even know where you are!")
        print("You have LOST AN ATTEMPT")
        currentScore = scoreUpdater(currentScore)
        menu(currentScore)

    elif job == "2":
        print("Ok, carry on...")
        print("Press Any Key to continue")
        x = input()
        print("Phew that was close!")
        print("The desk isnt opening though, I wouldn't try it again...")
        print("")
        menu(currentScore)

    elif job == "3":
        eyeArt()
        print("The security guard is not impressed")
        print("Press Any Key to continue")
        x = input()
        print("He says:")
        print("You dont even know where you are!")
        print("You have LOST AN ATTEMPT")
        currentScore = scoreUpdater(currentScore)
        menu(currentScore)
        
def action8(currentScore):
    print("You look around...no one is looking")
    print("You find the router and install the hardware")
    print("This MAN IN THE MIDDLE attack should get you tonnes of information!")
    print("Press Any Key to continue")
    x = input()
    print("Ok the data is coming through...")
    print("Press Any Key to continue")
    x = input()
    done = 1
    
    while done != 8:
        print("ENCRYPTED.ENCRYPTED.ENCRYPTED.ENCRYPTED.ENCRYPTED.")
        print("")
        print("v;ajwrbvajrkv a rvaenviwEVKJ V;ejvq34u584")
        print("wJVowuevhkwjvd saDK A`,XCANVB;OIEANRB;AW")
        print("cwEUBVQLIUWBEV AQKRBVQIUWREBVSADV BAUEBi")
        print("kcjadvkjabreubv   aowivwUBRALUWEVBVAkdsjvdn")
        print("cakjdwvbiquwrvlkawjebv ;IWEOBV;owuebv;wiEVBweuvb")
        print("")
        done = done + 1
        
    print("Press Any Key to continue")
    x = input()
    print("DAMN the data packets are Encrypted...")
    print("Looks like this didnt help!")
    print("Press Any Key to continue")
    x = input()
    menu(currentScore)


def action9(currentScore):
    print("Try a phishing attack...")
    print("You need an email address for them...do you have one?")
    print("Its probably their:")
    print("name...")
    print("@...")
    print("the domain...")
    print(".com...")
    print("")
    print("Enter the email address for the phishing attack")
    print("If you dont have the email, just hit Enter...")
    email = input()
    if email.upper() == "KELLYSMITH@KES.COM":
        print("Thats it!")
        print("You ping off an email, lets see if our victim bites...")
        time.sleep(0.2)
        print("Waiting.")
        time.sleep(0.2)
        print("Waiting..")
        time.sleep(0.2)
        print("Waiting...")
        time.sleep(0.2)
        print("Waiting....")
        time.sleep(0.2)
        print("Waiting.....")
        time.sleep(0.2)
        print("That it! They emailed Back!...")
        print("Lets see what valuable information they gave up...")
        print("Press Any Key to continue")
        x = input()
        phishingArt()
        print("Press Any Key to continue")
        x = input()
        print("Thats good info!")
        print("Dont forget to take it down!")
        print("Press Any Key to continue")
        x = input()
        menu(currentScore)
    else:
        print("I think you need to do some more investigation for a phishing attack to work...")
        print("Press Any Key to continue")
        x = input()
        menu(currentScore)

def action10(currentScore):
    print("Okay, time for the hack...")
    loginArt()
    guess = input()
    if guess.lower() == "kellysmith@kes.com":
        print("Thats the first part done!")
        passwordArt()
        guess2 = input()
        if guess2.lower() == "eddie07.11.20":
            print("Almost in!")
            print("Looks like they have 2 Factor Authentication...")
            print("Lets try and disable it...")
            print("We can get round it by answering a secret question!")
            questionArt()
            guess3 = input()
            if guess3.lower() == "luna":
                entryArt()
                print("Press Any Key to continue")
                x = input()
                print("You are in!")
                print("And you've found it...exactly what the hack was all about!!")
                print("Press Any Key to continue")
                x = input()
                catArt()
                print("Its a picture of Luna the cat!!!")
                print("Press Any Key to continue")
                x = input()
                hackArt()
            else:
                skullArt()
                print("Press Any Key to continue")
                x = input()
                print("You nearly had it")
                print("")
                currentScore = scoreUpdater(currentScore)
                menu(currentScore)
                
        else:
            skullArt()
            print("Press Any Key to continue")
            x = input()
            print("You nearly had it")
            print("")
            currentScore = scoreUpdater(currentScore)
            menu(currentScore)
            
    else:
        skullArt()
        print("Press Any Key to continue")
        x = input()
        print("You nearly had it")
        print("")
        currentScore = scoreUpdater(currentScore)
        menu(currentScore)
        
                
                
                
main()            
